osx_image: xcode8.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./install_docker.sh; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker pull nginx:1.13.12-alpine; fi
install:
- nvm install 10
- curl -o- -L https://yarnpkg.com/install.sh | bash
- source ~/.bashrc
- npm install -g xvfb-maybe
- yarn
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn run release; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run build:web; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build . -t registry.cn-hangzhou.aliyuncs.com/palan/electron-example; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker login --username=yuanzhencai@palan registry.cn-hangzhou.aliyuncs.com --password $ALI_REGISTRY_PASSWORD; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker push registry.cn-hangzhou.aliyuncs.com/palan/electron-example; fi
branches:
  only:
  - master
